### ISSUE TITLE
Issues while Using react.

### ISSUE THREAD

**Issue by cptiwari20** [calumk/editorjs-columns#8] opened 2023-04-25 04:14 UTC
I am using editorjs core module.
NOT "react-editor-js"

I found few  issues with it,

1. One alignment issues: ![image](https://user-images.githubusercontent.com/33618258/234172102-c1533007-890c-4dd5-81de-24d9e4d448ee.png)
2. The icons of the inline tool options got bolder. ![image](https://user-images.githubusercontent.com/33618258/234172256-7e1521ec-bac8-4dc6-82bf-c8306efc2962.png)
3. Not only in paragraphs,: On enter, lists and checkboxes also exit the current block.
4. And some errors while playing around with it,: ![image](https://user-images.githubusercontent.com/33618258/234172371-a39e2b0c-c128-48d0-bdfe-ff8c54071dee.png)
![image](https://user-images.githubusercontent.com/33618258/234172759-14819c9d-3300-4309-85df-318c65af0341.png)

MY GOAL OF RAISING THESE ISSUES,
I wanted to know if these are known issues or not
It is tested with react or any other framework, if yes, please attach some example.

**Comment by calumk** [comment] 2023-04-25 07:37
Not tested with React, but I am using with Vue - I have an update i can provide - I will push a new version

**Comment by N3M0dropserver** [comment] 2023-04-27 03:13
I'm encountering a similar issue but only with the boldness.
![image](https://user-images.githubusercontent.com/45587852/234750078-6bc62ee8-866e-4c38-b9d7-baafc34c862b.png)
Again this is using react and specifically the react-editorjs module.
Other then that its awesome code and am super impressed with it.

**Comment by calumk** [comment] 2023-04-27 10:28
Thanks - I have zero experiance with react unfortunatly - only Vue, but i recognise the issue of this bold icon, I think it is caused by some css stuff i did.
I will try to look into this.

I am glad people are using this plugin

**Comment by calumk** [comment] 2023-04-28 12:36
@N3M0dropserver  @cptiwari20  I have pushed an update that makes a significant (BREAKING) change. But might also help to solve this issue.

Previously, i was actually bundling EditorJs with the columns plugin, so there were in theory two versions of editorjs running simultainously. 
I suspect some of these visualisation issues were caused by css confilcts occouring here.

The new version removes the bundled EditorJs instance, and instead allows you to pass the library itself through it through as a property to the columns plugin. - eg: 

I believe this may help to solve the issue - please feel free to test

```javascript
 columns : {
        class : editorjsColumns,
        EditorJsLibrary : EditorJs // Pass the library instance to the columns instance.
        config : {
          tools : {
              header: Header,
              alert : Alert
        }
      },
```

**Comment by calumk** [comment] 2023-05-15 13:24
@N3M0dropserver @cptiwari20 Did this resolve the issue?

**Comment by N3M0dropserver** [comment] 2023-05-15 19:01
> @N3M0dropserver @cptiwari20 Did this resolve the issue? 

Haven't fully checked just yet will do later today sorry. Thanks for being so quick with a fix

**Comment by calumk** [comment] 2024-02-27 22:05
Closing as no update in ~ 1 Year.

**Closed by calumk** 2024-02-27 22:05 UTC
